<?php
/**
 * Implements hook_preprocess_block().
 */
function walnut_preprocess_block(array &$variables) {
  // start - reveal plugin_id values needed in block style plugins config
  // print '<pre>' . $variables['plugin_id'] . '</pre>';
  // end - reveal plugin_id values needed in block style plugins config
}

/**
 * Implements hook_form_alter().
 */
function walnut_form_alter(&$form, &$form_state, $form_id) {
  // dpm($form);
  // dpm($form_id);
  // if ($form_id == 'CONTENTTYPE_node_form') {
    /*
    * Modify the Add node button when it's the first one
    */
    // $form['MY_FIELD']['und']['form']['actions']['ief_add_save']['#value'] = t('CUSTOM TEXT');
    /*
    * Modify the Add node button when there is at least one node
    */
    // $form['MY_FIELD']['und']['actions']['ief_add']['#value'] = t('CUSTOM TEXT');
  // }
  
  // form_id = node_page_edit_form
/*  if (isset($form['MY_FIELD'][LANGUAGE_NONE]['entities'])) {
    foreach ($form['MY_FIELD'][LANGUAGE_NONE]['entities'] as $key => $entity_info) {
      if (is_numeric($key)) {
        $form['MY_FIELD'][LANGUAGE_NONE]['entities'][$key]['actions']['ief_entity_edit']['#value'] = t('CUSTOM TEXT');
        $form['MY_FIELD'][LANGUAGE_NONE]['entities'][$key]['actions']['ief_entity_remove']['#value'] = t('CUSTOM TEXT');
      }
    }
  }
*/
}